[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = "4.1.3"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"

aes-gcm = "0.10"
aead = "0.5"
hkdf = "0.12"
num-bigint = "0.4"
num-traits = "0.2"

